packages:
  - 'app'
  - 'tools'
  - 'tests'
  - 'options'
  - 'snap'
  - 'prisma'
  - 'package/node'
  - 'package/github'
  - 'package/vscode'
  - 'docs'

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
